name: pake-man

services:
  backend:
    environment:
      PAKE_MAN_COOKIE_SECRET: ${PAKE_MAN_COOKIE_SECRET}
      PAKE_MAN_DOMAIN_NAME: ${PAKE_MAN_DOMAIN_NAME}
      PAKE_MAN_FRONTEND_URL: http://127.0.0.1:3000
    networks:
      backend:
        aliases:
          - ${PAKE_MAN_DOMAIN_NAME}

  frontend:
    environment:
      PAKE_MAN_BACKEND_URL: http://${PAKE_MAN_DOMAIN_NAME}:3000
      PAKE_MAN_COOKIE_SECRET: ${PAKE_MAN_COOKIE_SECRET}
      PAKE_MAN_DOMAIN_NAME: ${PAKE_MAN_DOMAIN_NAME}
    networks:
      - backend
    depends_on:
      - backend

networks:
  backend:
    driver: bridge
