name: pake-man

services:
  backend:
    environment:
      PAKE_MAN_DOMAIN_NAME: ${PAKE_MAN_DOMAIN_NAME}
      PAKE_MAN_FRONTEND_URL: http://127.0.0.1:3000
    networks:
      - backend
      - elk

  frontend:
    environment:
      PAKE_MAN_BACKEND_URL: http://backend:3000
    networks:
      - backend
      - elk
    depends_on:
      - backend

networks:
  backend:
    driver: bridge
