name: pake-man

services:
  backend:
    environment:
      PAKE_MAN_FRONTEND_URL: http://127.0.0.1:3000
    networks:
      - backend

  frontend:
    environment:
      PAKE_MAN_BACKEND_URL: http://backend:3000
    networks:
      - backend
    depends_on:
      - backend

networks:
  backend:
    driver: bridge
