name: pake-man

services:
  frontend:
    build:
      context: .
    restart: always
    environment:
      PAKE_MAN_SERVER_CLOSE_GRACE_DELAY: ${PAKE_MAN_SERVER_CLOSE_GRACE_DELAY}
      PAKE_MAN_SERVER_HOST: 0.0.0.0
      PAKE_MAN_SERVER_PORT: 3000
    ports:
      - 3000:3000
