name: pake-man

services:
  frontend:
    build:
      context: .
    restart: always
    environment:
      PAKE_MAN_COOKIE_SECRET: ${PAKE_MAN_COOKIE_SECRET}
      PAKE_MAN_CSRF_PROTECTION_HMAC_KEY: ${PAKE_MAN_CSRF_PROTECTION_HMAC_KEY}
      PAKE_MAN_DOMAIN_NAME: ${PAKE_MAN_DOMAIN_NAME}
      PAKE_MAN_OAUTH2_GOOGLE_CALLBACK_URI: ${PAKE_MAN_OAUTH2_GOOGLE_CALLBACK_URI}
      PAKE_MAN_OAUTH2_GOOGLE_CLIENT_ID: ${PAKE_MAN_OAUTH2_GOOGLE_CLIENT_ID}
      PAKE_MAN_OAUTH2_GOOGLE_CLIENT_SECRET: ${PAKE_MAN_OAUTH2_GOOGLE_CLIENT_SECRET}
      PAKE_MAN_SERVER_CLOSE_GRACE_DELAY: ${PAKE_MAN_SERVER_CLOSE_GRACE_DELAY}
      PAKE_MAN_SERVER_HOST: 0.0.0.0
      PAKE_MAN_SERVER_PORT: 3000
    ports:
      - 3000:3000
